components:
  schemas:
    putInventoryRequest:
      type: object
      properties:
        quantity:
          type: number
        size:
          type: string
        frontImage:
          type: string
          format: binary
        backImage:
          type: string
          format: binary
    putInventoryResponse:
      type: object
      properties:
        message:
          type: string
    errorSchema:
      properties:
        message:
          type: string
        code:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /products/{productId}/inventory/{inventoryId}:
    put:
      tags:
        - inventory
      summary: Update inventory
      description: Update inventory of a product
      parameters:
        - name: productId
          in: path
          description: Product Id
          required: true
          schema:
            type: string
        - name: inventoryId
          in: path
          description: Inventory Id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/putInventoryRequest'
      responses:
        '204':
          description: Request processed successfully!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/putInventoryResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/errorSchema'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/errorSchema'
      security:
        - bearerAuth: []
